version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy-wide.conf:/etc/nginx/conf.d/proxy-wide.conf:ro
      - ../certs/domains:/etc/nginx/certs
    networks:
      - nginx_proxy_network

networks:
  nginx_proxy_network:
    external: true
